Repository googleapis/nodejs-cloudbuild, pull requests merged in 2020-05, with the labels that each got.

#114 feat: check status of long running operation by its name
  src/v1/cloud_build_client.ts
  synth.metadata
  test/gapic_cloud_build_v1.ts
Labels: automerge, cla: yes

#115 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#116 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
