Repository googleapis/nodejs-cloudbuild, pull requests merged in 2020-07, with the labels that each got.

#128 chore: set Ruby namespace in proto options
  protos/google/devtools/cloudbuild/v1/cloudbuild.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full

#130 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#131 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#132 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#135 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#136 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#137 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#141 fix: add missing cloudbuild RPCs to retry config, add Node 8 tests 
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  src/v1/cloud_build_client_config.json
  synth.metadata
Labels: cla: yes, context: partial

#142 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#144 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#145 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 docs: inline markup spans must be separated from the surrounding text by non-word characters
  protos/google/devtools/cloudbuild/v1/cloudbuild.proto
  src/v1/cloud_build_client.ts
  synth.metadata
Labels: cla: yes, context: full

#147 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#149 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#150 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
