Repository googleapis/nodejs-cloudbuild, pull requests merged in 2020-11, with the labels that each got.

#177 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#181 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/cloud_build_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudbuild, automerge, cla: yes

#185 fix: check for fetch on window
  protos/protos.json
  src/v1/cloud_build_client.ts
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: none

#187 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full
